spring.application.name=the-omen
spring.datasource.url=jdbc:mysql://localhost:3306/the_omen_spring_boot
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format-sql=true


